services:
  - type: web
    name: marom-backend
    env: node
    nodeVersion: 18.17.0
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
